/**
 * WordPress dependencies
 */
import { __ } from '@wordpress/i18n';
import { useBlockProps } from '@wordpress/block-editor';

/**
 * Edit component for the breadcrumbs block.
 *
 * This is a dynamic block — the real breadcrumb trail is generated by
 * render.php at render time. The editor only needs a static placeholder
 * so the block doesn't appear blank or error while inserted.
 *
 * @param {Object} props Block props.
 * @return {Element} Element to render.
 */
export default function Edit() {
	const blockProps = useBlockProps( {
		className: 'ls-crumbs-placeholder',
	} );

	return (
		<nav { ...blockProps } aria-label={ __( 'Breadcrumb', 'ls-plugin' ) }>
			<span>{ __( 'Breadcrumbs (dynamic)', 'ls-plugin' ) }</span>
		</nav>
	);
}
